name: tests
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17 # 此处的JDK版本要同maven pom.xml文件中一致
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: "${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}"
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml # 这里具体到自己的pom.xml文件位置

  merge:
    runs-on: ubuntu-latest
    needs: run_tests
    if: github.event_name == 'pull_request' && github.event.action == 'synchronize' && success() # 确保是 PR 并且测试成功
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Merge PR
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout ${{ github.head_ref }} # 切换到 PR 分支
          git merge origin/main # 合并主分支到 PR
          git push origin ${{ github.head_ref }}:refs/heads/${{ github.head_ref }}